# =============================================================================
# ROS2 Control Configuration for Rover Simulation
# =============================================================================
# Controller configuration for 4WD rover with differential drive kinematics
# Optimized for Traxxas Rustler 4x4 VXL physical parameters
# =============================================================================

controller_manager:
  ros__parameters:
    update_rate: 100  # Hz
    
    # Controller plugins
    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController
    
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

# Differential Drive Controller Configuration
diff_drive_controller:
  ros__parameters:
    # Wheel joint names (4WD grouped as left/right)
    left_wheel_names: ["front_left_wheel_joint", "rear_left_wheel_joint"]
    right_wheel_names: ["front_right_wheel_joint", "rear_right_wheel_joint"]
    
    # Physical parameters (Traxxas Rustler 4x4 VXL)
    wheel_separation: 0.4    # meters (track width)
    wheel_radius: 0.08       # meters
    
    # Publishing settings
    publish_rate: 50.0       # Hz
    odom_frame_id: "odom"
    base_frame_id: "base_footprint"
    pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    
    # Control settings
    open_loop: false         # Use closed-loop control
    enable_odom_tf: true     # Publish odometry transform
    cmd_vel_timeout: 0.5     # seconds
    
    # Velocity limits
    linear:
      x:
        has_velocity_limits: true
        has_acceleration_limits: true
        has_jerk_limits: false
        max_velocity: 2.0     # m/s
        min_velocity: -2.0    # m/s
        max_acceleration: 1.0 # m/s^2
        min_acceleration: -1.0 # m/s^2
    
    angular:
      z:
        has_velocity_limits: true
        has_acceleration_limits: true
        has_jerk_limits: false
        max_velocity: 2.0     # rad/s
        min_velocity: -2.0    # rad/s
        max_acceleration: 1.0 # rad/s^2
        min_acceleration: -1.0 # rad/s^2

# Joint State Broadcaster Configuration
joint_state_broadcaster:
  ros__parameters:
    joints:
      - front_left_wheel_joint
      - front_right_wheel_joint
      - rear_left_wheel_joint
      - rear_right_wheel_joint
    interfaces:
      - position
      - velocity