name: Docker

on:
  schedule:
    - cron: '41 13 * * *'
  push:
    branches: [ "master" ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install cosign
        if: github.event_name != 'pull_request'
        uses: sigstore/cosign-installer@59acb6260d9c0ba8f4a2f9d9b48431a222b68e20 #v3.5.0
        with:
          cosign-release: 'v2.2.4'

      - name: Log into registry ghcr.io
        if: github.event_name != 'pull_request'
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build all images
        run: make all

      - name: Push images
        if: github.event_name != 'pull_request'
        run: make publish-latest

      - name: Sign images
        if: github.event_name != 'pull_request'
        run: |
          GIT_TAG=$(git describe --tags --exact-match 2>/dev/null || git rev-parse --short HEAD)
          cosign sign --yes ghcr.io/wkronmiller/docker-ros-base:${GIT_TAG}
          cosign sign --yes ghcr.io/wkronmiller/docker-ros-gazebo:${GIT_TAG}
          cosign sign --yes ghcr.io/wkronmiller/docker-ros-gazebo-gui:${GIT_TAG}
